<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart 
// this is an autogenerated file - do not edit
spl_autoload_register(
   function( $class )
   {
      static $classes = null;
      if ( $classes === null )
      {
         $classes = array(
            'olap4php\\common\\ienum'                                          => '/common/IEnum.php',
            'olap4php\\common\\logger'                                         => '/common/Logger.php',
            'olap4php\\common\\namedlist'                                      => '/common/NamedList.php',
            'olap4php\\common\\properties'                                     => '/common/Properties.php',
            'olap4php\\common\\resultset'                                      => '/common/ResultSet.php',
            'olap4php\\common\\util'                                           => '/common/Util.php',
            'olap4php\\common\\wildcard'                                       => '/common/Wildcard.php',
            'olap4php\\metadata\\aggregator'                                   => '/metadata/Aggregator.php',
            'olap4php\\metadata\\datatype'                                     => '/metadata/DataType.php',
            'olap4php\\metadata\\dictionary'                                   => '/metadata/Dictionary.php',
            'olap4php\\metadata\\dimensiontype'                                => '/metadata/DimensionType.php',
            'olap4php\\metadata\\icatalog'                                     => '/metadata/ICatalog.php',
            'olap4php\\metadata\\icube'                                        => '/metadata/ICube.php',
            'olap4php\\metadata\\idimension'                                   => '/metadata/IDimension.php',
            'olap4php\\metadata\\ihierarchy'                                   => '/metadata/IHierarchy.php',
            'olap4php\\metadata\\ilevel'                                       => '/metadata/ILevel.php',
            'olap4php\\metadata\\imeasure'                                     => '/metadata/IMeasure.php',
            'olap4php\\metadata\\imember'                                      => '/metadata/IMember.php',
            'olap4php\\metadata\\imetadataelement'                             => '/metadata/IMetadataElement.php',
            'olap4php\\metadata\\inamed'                                       => '/metadata/INamed.php',
            'olap4php\\metadata\\inamedlist'                                   => '/metadata/INamedList.php',
            'olap4php\\metadata\\inamedset'                                    => '/metadata/INamedSet.php',
            'olap4php\\metadata\\iposition'                                    => '/metadata/IType.php',
            'olap4php\\metadata\\iproperty'                                    => '/metadata/IProperty.php',
            'olap4php\\metadata\\ischema'                                      => '/metadata/ISchema.php',
            'olap4php\\metadata\\ixmlaconstant'                                => '/metadata/IXMLAConstant.php',
            'olap4php\\metadata\\ixmlaconstantdictionary'                      => '/metadata/IXMLAConstantDictionary.php',
            'olap4php\\metadata\\leveltype'                                    => '/metadata/LevelType.php',
            'olap4php\\metadata\\membertype'                                   => '/metadata/MemberType.php',
            'olap4php\\metadata\\propertycontenttype'                          => '/metadata/PropertyContentType.php',
            'olap4php\\metadata\\propertytype'                                 => '/metadata/PropertyType.php',
            'olap4php\\metadata\\standardmemberproperty'                       => '/metadata/StandardMemberProperty.php',
            'olap4php\\olap\\axis'                                             => '/olap/Axis.php',
            'olap4php\\olap\\iaxis'                                            => '/olap/IAxis.php',
            'olap4php\\olap\\icell'                                            => '/olap/ICell.php',
            'olap4php\\olap\\icellset'                                         => '/olap/ICellSet.php',
            'olap4php\\olap\\icellsetaxis'                                     => '/olap/ICellSetAxis.php',
            'olap4php\\olap\\icellsetaxismetadata'                             => '/olap/ICellSetAxisMetaData.php',
            'olap4php\\olap\\icellsetmetadata'                                 => '/olap/ICellSetMetaData.php',
            'olap4php\\olap\\iolapconnection'                                  => '/olap/IOLAPConnection.php',
            'olap4php\\olap\\iolapdatabasemetadata'                            => '/olap/IOLAPDatabaseMetaData.php',
            'olap4php\\olap\\iolapstatement'                                   => '/olap/IOLAPStatement.php',
            'olap4php\\olap\\iposition'                                        => '/olap/IPosition.php',
            'olap4php\\olap\\olapexception'                                    => '/olap/OLAPException.php',
            'olap4php\\olap\\provider\\xmla\\xmlapositionmember'               => '/provider/xmla/XMLAPositionMember.php',
            'olap4php\\provider\\caching\\drivers\\mcache'                     => '/provider/caching/drivers/MCache.php',
            'olap4php\\provider\\caching\\ixmlacache'                          => '/provider/caching/IXMLACache.php',
            'olap4php\\provider\\xmla\\ixmlamember'                            => '/provider/xmla/IXMLAMember.php',
            'olap4php\\provider\\xmla\\metadata\\ixmlametadatahandler'         => '/provider/xmla/metadata/IXMLAMetadataHandler.php',
            'olap4php\\provider\\xmla\\metadata\\ixmlametadatareader'          => '/provider/xmla/metadata/IXMLAMetadataReader.php',
            'olap4php\\provider\\xmla\\metadata\\lazymetadatalist'             => '/provider/xmla/metadata/LazyMetadataList.php',
            'olap4php\\provider\\xmla\\metadata\\xmlacachingmetadatareader'    => '/provider/xmla/metadata/XMLACachingMetadataReader.php',
            'olap4php\\provider\\xmla\\metadata\\xmlacataloghandler'           => '/provider/xmla/metadata/XMLACatalogHandler.php',
            'olap4php\\provider\\xmla\\metadata\\xmlacatalogschemahandler'     => '/provider/xmla/metadata/XMLACatalogSchemaHandler.php',
            'olap4php\\provider\\xmla\\metadata\\xmlacubehandler'              => '/provider/xmla/metadata/XMLACubeHandler.php',
            'olap4php\\provider\\xmla\\metadata\\xmladelegatingmetadatareader' => '/provider/xmla/metadata/XMLADelegatingMetadataReader.php',
            'olap4php\\provider\\xmla\\metadata\\xmladimensionhandler'         => '/provider/xmla/metadata/XMLADimensionHandler.php',
            'olap4php\\provider\\xmla\\metadata\\xmlahierarchyhandler'         => '/provider/xmla/metadata/XMLAHierarchyHandler.php',
            'olap4php\\provider\\xmla\\metadata\\xmlalevelhandler'             => '/provider/xmla/metadata/XMLALevelHandler.php',
            'olap4php\\provider\\xmla\\metadata\\xmlameasurehandler'           => '/provider/xmla/metadata/XMLAMeasureHandler.php',
            'olap4php\\provider\\xmla\\metadata\\xmlamemberhandler'            => '/provider/xmla/metadata/XMLAMemberHandler.php',
            'olap4php\\provider\\xmla\\metadata\\xmlametadatahandler'          => '/provider/xmla/metadata/XMLAMetadataHandler.php',
            'olap4php\\provider\\xmla\\metadata\\xmlametadatareader'           => '/provider/xmla/metadata/XMLAMetadataReader.php',
            'olap4php\\provider\\xmla\\metadata\\xmlanamedsethandler'          => '/provider/xmla/metadata/XMLANamedSetHandler.php',
            'olap4php\\provider\\xmla\\metadata\\xmlapropertyhandler'          => '/provider/xmla/metadata/XMLAPropertyHandler.php',
            'olap4php\\provider\\xmla\\xmlacatalog'                            => '/provider/xmla/XMLACatalog.php',
            'olap4php\\provider\\xmla\\xmlacell'                               => '/provider/xmla/XMLACell.php',
            'olap4php\\provider\\xmla\\xmlacellproperty'                       => '/provider/xmla/XMLACellProperty.php',
            'olap4php\\provider\\xmla\\xmlacellset'                            => '/provider/xmla/XMLACellSet.php',
            'olap4php\\provider\\xmla\\xmlacellsetaxis'                        => '/provider/xmla/XMLACellSetAxis.php',
            'olap4php\\provider\\xmla\\xmlacellsetaxismetadata'                => '/provider/xmla/XMLACellSetAxisMetaData.php',
            'olap4php\\provider\\xmla\\xmlacellsetmemberproperty'              => '/provider/xmla/XMLACellSetMemberProperty.php',
            'olap4php\\provider\\xmla\\xmlacellsetmetadata'                    => '/provider/xmla/XMLACellSetMetaData.php',
            'olap4php\\provider\\xmla\\xmlaconnection'                         => '/provider/xmla/XMLAConnection.php',
            'olap4php\\provider\\xmla\\xmlaconnectioncontext'                  => '/provider/xmla/XMLAConnectionContext.php',
            'olap4php\\provider\\xmla\\xmlacube'                               => '/provider/xmla/XMLACube.php',
            'olap4php\\provider\\xmla\\xmladatabasemetadata'                   => '/provider/xmla/XMLADatabaseMetaData.php',
            'olap4php\\provider\\xmla\\xmladimension'                          => '/provider/xmla/XMLADimension.php',
            'olap4php\\provider\\xmla\\xmlaelement'                            => '/provider/xmla/XMLAElement.php',
            'olap4php\\provider\\xmla\\xmlahierarchy'                          => '/provider/xmla/XMLAHierarchy.php',
            'olap4php\\provider\\xmla\\xmlalevel'                              => '/provider/xmla/XMLALevel.php',
            'olap4php\\provider\\xmla\\xmlameasure'                            => '/provider/xmla/XMLAMeasure.php',
            'olap4php\\provider\\xmla\\xmlamember'                             => '/provider/xmla/XMLAMember.php',
            'olap4php\\provider\\xmla\\xmlamemberundefined'                    => '/provider/xmla/XMLAMemberUndefined.php',
            'olap4php\\provider\\xmla\\xmlametadatacolumn'                     => '/provider/xmla/XMLAMetadataColumn.php',
            'olap4php\\provider\\xmla\\xmlametadatarequest'                    => '/provider/xmla/XMLAMetadataRequest.php',
            'olap4php\\provider\\xmla\\xmlanamedset'                           => '/provider/xmla/XMLANamedSet.php',
            'olap4php\\provider\\xmla\\xmlaposition'                           => '/provider/xmla/XMLAPosition.php',
            'olap4php\\provider\\xmla\\xmlaproperty'                           => '/provider/xmla/XMLAProperty.php',
            'olap4php\\provider\\xmla\\xmlaschema'                             => '/provider/xmla/XMLASchema.php',
            'olap4php\\provider\\xmla\\xmlastatement'                          => '/provider/xmla/XMLAStatement.php',
            'olap4php\\provider\\xmla\\xmlatreeop'                             => '/provider/xmla/XMLATreeOp.php',
            'olap4php\\provider\\xmla\\xmlautil'                               => '/provider/xmla/XMLAUtil.php'
         );
      }
      $cn = strtolower( $class );
      if ( isset($classes[$cn]) )
      {
         require __DIR__ . $classes[$cn];
      }
   }
);
// @codeCoverageIgnoreEnd
